URL = "http://localhost/"
AllowedHosts = ["localhost"]
ExcludedURIs = ["/setup.php", "/logout.php", "/security.php"]
DataPath = "browserktmp"
NumBrowsers = 10
MaxDepth = 4
JSPluginPath = "plugins/"

[FormData]
UserName  = "admin"
Password = "password"