URL = "http://localhost/"
AllowedHosts = ["localhost"]
ExcludedURIs = ["/setup.php", "/logout.php", "/security.php"]
DataPath = "browserktmp"
NumBrowsers = 5
MaxDepth = 25
JSPluginPath = "plugins/"

[FormData]
UserName  = "admin"
Password = "password"