URL = "http://browserker.gitlab.pwn/users/sign_in"
AllowedHosts = ["browserker.gitlab.pwn"]
ExcludedURIs = ["/help", "/help/", "/profile/password/edit", "/users/sign_out", "/explore"]
DataPath = "browserktmp"
DisableHeadless = false
NumBrowsers = 6
MaxDepth = 10
MaxActions = 100
JSPluginPath = "plugins/"

[FormData]
Email = "test@test.com"
UserName  = "test@test.com"
Password = "testpass"