URL = "http://browserker.gitlab.pwn/users/sign_in"
AllowedHosts = ["browserker.gitlab.pwn"]
ExcludedURIs = ["/help", "/help/", "/profile/password/edit", "/users/sign_out"]
DataPath = "browserktmp"
DisableHeadless = false
NumBrowsers = 6
MaxDepth = 10
JSPluginPath = "plugins/"

[FormData]
UserName  = "test2@test.com"
Password = "testpass123"