URL = "http://localhost:3000/#/login"
AllowedHosts = ["localhost"]
DataPath = "browserktmp"
DisableHeadless = false
NumBrowsers = 7
MaxDepth = 25
JSPluginPath = "plugins/"

[CustomCookies]
welcomebanner_status = "dismiss"
cookieconsent_status = "dismiss"

[FormData]
UserName  = "test@test.com"
Email = "test@test.com"
Password = "testtest"